import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class HTML_Generator {
    String html = "";

    public String getHTML() {
        return html;
    }

    public void editHTML(String input) {
        html += input;
    }

    static void printMenu() {
        System.out.println();
        System.out.println("--> Heading нэмэх \"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6 , \"h7\"");
        System.out.println("--> Paragraph нэмэх \"p\"");
        System.out.println("--> Anchor нэмэх \"a\"");
        System.out.println("--> Bold text нэмэх\"b\"");
        System.out.println("--> Догол мөр авах \"br\"");
        System.out.println("--> code бичих \"code\"");
        System.out.println("--> Зураг нэмэх \"img\"");
        System.out.println("--> Quote нэмэх \"q\"");
        System.out.println("--> Sub текст нэмэх \"sub\"");
        System.out.println("--> Sup текст нэмэх \"sup\"");
        System.out.println("--> Italic текст нэмэх \"i\"");
        System.out.println("--> Strong текст нэмэх \"strong\"");
        System.out.println("--> Unordered List нэмэх \"ul\"");
        System.out.println("--> Unordered List нэмэх \"ol\"");
        System.out.println("--> хадгалах");
        System.out.println("--> гарах");
    }

    static void uiMenu() {
        System.out.println("1. Шинэ хуудас үүсгэх");
    }

    void save(String html) {
        Scanner scanner = new Scanner(System.in);
        String text = "";
        System.out.println("Файлын нэрийг юу гэж өгөх вэ?");
        text = scanner.nextLine();

        File file = new File(text + ".html");
        try {
            if (file.createNewFile()) {
                System.out.println("За файл үүслээ2");
                FileWriter myWriter = new FileWriter(file);
                myWriter.write(html);
                myWriter.close();

                System.out.println("Файл амжилттай үүслээ: " + file.getName());
            } else {
                System.out.println("Файлд өөрчлөлт амжилттай хадгалагдлаа: " + file.getName());
            }
        } catch (IOException e) {
            System.out.println("Файлд өөрчлөлт хадгалахад алдаа гарлаа: " + e);

        }
        System.out.println("PATH: " + file.getAbsolutePath());
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        HTML_Generator generator = new HTML_Generator();

        generator.editHTML("<!DOCTYPE html>\n");
        generator.editHTML("<html>\n");
        generator.editHTML("<head>\n");
        generator.editHTML("<title>HTML Page Generated by \"Java HTML Generator\"</title>\n");
        generator.editHTML("</head>\n");
        generator.editHTML("<body>\n");

        String text;
        for (;;) {
            printMenu();
            String input = scanner.nextLine();

            if (input.equals("h1") ||
                    input.equals("h2") ||
                    input.equals("h3") ||
                    input.equals("h4") ||
                    input.equals("h5") ||
                    input.equals("h6") ||
                    input.equals("h7") ||
                    input.equals("p") ||
                    input.equals("b") ||
                    input.equals("code") ||
                    input.equals("sub") ||
                    input.equals("q") ||
                    input.equals("sup") ||
                    input.equals("strong") ||
                    input.equals("i") ||
                    input.equals("small")) {
                System.out.println("Tag-ийн текстийг оруулна уу");

                text = scanner.nextLine();

                generator.editHTML("<" + input + ">" + text + "</" + input + ">");
            } else if (input.equals("br")) {

                generator.editHTML("<br>");

            } else if (input.equals("img")) {
                System.out.println("Зургийн замыг зааж өгнө үү");
                text = scanner.nextLine();

                System.out.print("Зургийн өргөн:");
                String width = scanner.nextLine();
                System.out.print("Зургийн урт:");
                String height = scanner.nextLine();
                System.out.print("alt текст:");
                String alt = scanner.nextLine();

                generator.editHTML(
                        "<img src=\"" + text + "\" width=\"" + width + "\" height=\"" + height + " \" alt=\"" + alt
                                + "\"/>");
            } else if (input.equals("ul") || input.equals("ol")) {
                System.out.print("Оруулах листийн тоог оруулна уу: ");
                int numItems = Integer.parseInt(scanner.nextLine());
                generator.editHTML("<" + input + ">\n");
                for (int i = 0; i < numItems; i++) {
                    System.out.print((i + 1) + ": ");
                    String listItem = scanner.nextLine();
                    generator.editHTML("<li>" + listItem + "</li>\n");
                }
                generator.editHTML("</" + input + ">\n");

            } else if (input.equals("a")) {
                System.out.print("Anchor tag-ны текстийг оруулна уу: ");
                String linkText = scanner.nextLine();
                System.out.print("Anchor tag-ны URL: ");
                String url = scanner.nextLine();
                generator.editHTML("<a href=\"" + url + "\">" + linkText + "</a>\n");
            } else if (input.equals("хадгалах")) {
                generator.save(generator.getHTML());
            } else if (input.equals("гарах")) {
                break;
            }
        }
        generator.editHTML("</body>\n");
        generator.editHTML("</html>\n");

        generator.save(generator.getHTML());
        System.out.println(":" + generator.getHTML());
    }
}